name: DB Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'src/drizzle/schema.ts'
      - 'migrations/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/drizzle/schema.ts'
      - 'migrations/**'

jobs:
  migrations:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # 或您使用的 pnpm 版本
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate migration
        run: pnpm db:generate

      - name: Apply migrations
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            pnpm db:push
          else
            pnpm drizzle-kit check
          fi
